
import os
try:
    from fpdf import FPDF
except ImportError:
    print("FPDF library not found. Please run 'pip install fpdf' to generate PDFs.")
    exit(1)

OUTPUT_DIR = "uploads/scenario_1"
os.makedirs(OUTPUT_DIR, exist_ok=True)

class FreightPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'FREIGHT DOCUMENT', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def create_invoice():
    pdf = FreightPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("Arial", "B", 20)
    pdf.cell(0, 10, "INVOICE", ln=True, align="C")
    
    # Vendor Details
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "TCI Express Limited", ln=True)
    pdf.set_font("Arial", "", 10)
    pdf.cell(0, 5, "TCI House, 69 Institutional Area,", ln=True)
    pdf.cell(0, 5, "Sector-32, Gurgaon - 122001", ln=True)
    pdf.cell(0, 5, "GSTIN: 06AAACT6246H1Z8", ln=True)
    pdf.ln(10)
    
    # Invoice Details
    pdf.set_font("Arial", "B", 12)
    pdf.cell(100, 10, "Bill To:", 0, 0)
    pdf.cell(0, 10, "Invoice Details:", 0, 1)
    
    pdf.set_font("Arial", "", 10)
    pdf.cell(100, 5, "Confidential Client Ltd (Enterprise)", 0, 0)
    pdf.cell(0, 5, "Invoice #: DEMO/2024/PERFECT", 0, 1)
    
    pdf.cell(100, 5, "Mumbai, Maharashtra", 0, 0)
    pdf.cell(0, 5, "Date: 2024-12-28", 0, 1)

    pdf.cell(100, 5, "GSTIN: 27AABCC9999R1Z1", 0, 0)
    pdf.cell(0, 5, "Due Date: 2025-01-28", 0, 1)
    pdf.ln(10)

    # Line Items Table Header
    pdf.set_fill_color(200, 220, 255)
    pdf.set_font("Arial", "B", 10)
    pdf.cell(120, 10, "Description", 1, 0, 'C', 1)
    pdf.cell(30, 10, "HSN/SAC", 1, 0, 'C', 1)
    pdf.cell(40, 10, "Amount (INR)", 1, 1, 'C', 1)

    # Items
    pdf.set_font("Arial", "", 10)
    pdf.cell(120, 10, "LTL Transportation - Mumbai to Delhi (500kg)", 1)
    pdf.cell(30, 10, "996511", 1)
    pdf.cell(40, 10, "10,593.00", 1, 1, 'R')

    pdf.cell(120, 10, "CGST (9%)", 1)
    pdf.cell(30, 10, "", 1)
    pdf.cell(40, 10, "953.00", 1, 1, 'R')

    pdf.cell(120, 10, "SGST (9%)", 1)
    pdf.cell(30, 10, "", 1)
    pdf.cell(40, 10, "954.00", 1, 1, 'R')

    # Total
    pdf.set_font("Arial", "B", 12)
    pdf.cell(150, 10, "TOTAL AMOUNT", 1)
    pdf.cell(40, 10, "12,500.00", 1, 1, 'R')
    
    pdf.ln(10)
    pdf.set_font("Arial", "I", 10)
    pdf.cell(0, 10, "Generated by Atlas Simulation Engine", ln=True, align="C")

    filename = os.path.join(OUTPUT_DIR, "DEMO_PERFECT_INV.pdf")
    pdf.output(filename)
    print(f"Generated: {filename}")

def create_lr():
    pdf = FreightPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 20)
    pdf.cell(0, 10, "LORRY RECEIPT (LR)", ln=True, align="C")
    
    pdf.set_font("Arial", "", 12)
    pdf.ln(10)
    pdf.cell(0, 10, "LR Number: LR-8899", ln=True)
    pdf.cell(0, 10, "Date: 2024-12-25", ln=True)
    pdf.cell(0, 10, "Origin: Mumbai Hub", ln=True)
    pdf.cell(0, 10, "Destination: Delhi Okhla", ln=True)
    pdf.cell(0, 10, "Consignor: Confidential Client Mumbai", ln=True)
    pdf.cell(0, 10, "Consignee: Confidential Client Delhi", ln=True)
    pdf.cell(0, 10, "Weight: 500 KG", ln=True)
    pdf.cell(0, 10, "No of Pkgs: 25 Boxes", ln=True)
    
    filename = os.path.join(OUTPUT_DIR, "LR_DEMO_PERFECT.pdf")
    pdf.output(filename)
    print(f"Generated: {filename}")

def create_pod():
    pdf = FreightPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 20)
    pdf.cell(0, 10, "PROOF OF DELIVERY (POD)", ln=True, align="C")
    
    pdf.set_font("Arial", "", 12)
    pdf.ln(10)
    pdf.cell(0, 10, "Ref LR Number: LR-8899", ln=True)
    pdf.cell(0, 10, "Delivery Date: 2024-12-29 14:30", ln=True)
    pdf.cell(0, 10, "Received By: Warehouse In-charge", ln=True)
    pdf.cell(0, 10, "Condition: GOOD", ln=True)
    
    pdf.ln(20)
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "[ SIGNED & STAMPED ]", ln=True, align="C")
    
    filename = os.path.join(OUTPUT_DIR, "POD_DEMO_PERFECT.pdf")
    pdf.output(filename)
    print(f"Generated: {filename}")

def create_contract():
    pdf = FreightPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 20)
    pdf.cell(0, 10, "RATE CONTRACT 2024-25", ln=True, align="C")
    
    pdf.set_font("Arial", "", 12)
    pdf.ln(10)
    pdf.cell(0, 10, "Carrier: TCI Express Limited", ln=True)
    pdf.cell(0, 10, "Valid From: 01-Jan-2024 to 31-Dec-2025", ln=True)
    pdf.ln(10)
    
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "Agreed Rates:", ln=True)
    
    pdf.set_font("Arial", "", 10)
    pdf.cell(100, 10, "Lane: Mumbai to Delhi (Surface)", 1)
    pdf.cell(50, 10, "Rate: INR 21.00 / kg", 1, 1)
    
    pdf.cell(100, 10, "Min Charge", 1)
    pdf.cell(50, 10, "INR 1500.00", 1, 1)
    
    pdf.cell(100, 10, "Docket Charge", 1)
    pdf.cell(50, 10, "INR 93.00", 1, 1)

    # 500kg * 21 = 10500 + 93 = 10593. Matches invoice base.
    
    filename = os.path.join(OUTPUT_DIR, "CONTRACT_DEMO.pdf")
    pdf.output(filename)
    print(f"Generated: {filename}")

if __name__ == "__main__":
    create_invoice()
    create_lr()
    create_pod()
    create_contract()
