"""
Generate Demo Invoice PDFs and Update Database
===============================================
This script:
1. Fetches all invoices from PostgreSQL database
2. Generates a professional PDF for each invoice
3. Saves PDFs to uploads/invoices/{id}/ folder
4. Updates the database pdf_path field
"""

import psycopg2
import os
from dotenv import load_dotenv
from datetime import datetime
from pathlib import Path

# Try FPDF first, fallback to reportlab
try:
    from fpdf import FPDF
    HAS_FPDF = True
except ImportError:
    HAS_FPDF = False
    try:
        from reportlab.pdfgen import canvas
        from reportlab.lib.pagesizes import A4
        HAS_REPORTLAB = True
    except ImportError:
        HAS_REPORTLAB = False

load_dotenv()
DATABASE_URL = os.getenv("DATABASE_URL")

# Create uploads directory
UPLOAD_DIR = Path(__file__).parent / "uploads" / "invoices"
UPLOAD_DIR.mkdir(parents=True, exist_ok=True)


def generate_pdf_fpdf(invoice: dict, output_path: str):
    """Generate invoice PDF using FPDF library"""
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "TAX INVOICE", 0, 1, "C")
    pdf.ln(5)
    
    # Invoice Details Box
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, f"Invoice #: {invoice['invoice_number']}", 0, 1)
    pdf.set_font("Arial", "", 10)
    pdf.cell(0, 6, f"Date: {invoice.get('invoice_date', 'N/A')}", 0, 1)
    pdf.cell(0, 6, f"Due Date: {invoice.get('due_date', 'N/A')}", 0, 1)
    pdf.ln(5)
    
    # Vendor Details
    pdf.set_font("Arial", "B", 11)
    pdf.cell(0, 8, "From:", 0, 1)
    pdf.set_font("Arial", "", 10)
    pdf.cell(0, 6, f"{invoice.get('vendor_name', 'Carrier')}", 0, 1)
    pdf.cell(0, 6, f"GSTIN: 27AABCT1234R1Z5", 0, 1)
    pdf.ln(5)
    
    # Shipment Details
    pdf.set_font("Arial", "B", 11)
    pdf.cell(0, 8, "Shipment Details:", 0, 1)
    pdf.set_font("Arial", "", 10)
    pdf.cell(95, 6, f"Origin: {invoice.get('origin', 'N/A')}", 0, 0)
    pdf.cell(95, 6, f"Destination: {invoice.get('destination', 'N/A')}", 0, 1)
    pdf.cell(95, 6, f"LR Number: {invoice.get('lr_number', 'N/A')}", 0, 0)
    pdf.cell(95, 6, f"Mode: {invoice.get('mode', 'Road')}", 0, 1)
    pdf.cell(95, 6, f"Weight: {invoice.get('weight_kg', 0)} kg", 0, 0)
    pdf.cell(95, 6, f"Distance: {invoice.get('distance_km', 0)} km", 0, 1)
    pdf.ln(5)
    
    # Line separator
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
    
    # Amount Section
    pdf.set_font("Arial", "B", 11)
    pdf.cell(0, 8, "Charges:", 0, 1)
    pdf.set_font("Arial", "", 10)
    
    base_amount = float(invoice.get('base_amount', 0) or invoice.get('amount', 0) or 0)
    gst_amount = float(invoice.get('gst_amount', 0) or base_amount * 0.18)
    total = float(invoice.get('amount', 0) or base_amount + gst_amount)
    
    pdf.cell(140, 6, "Base Freight:", 0, 0)
    pdf.cell(50, 6, f"Rs. {base_amount:,.2f}", 0, 1, "R")
    pdf.cell(140, 6, "GST (18%):", 0, 0)
    pdf.cell(50, 6, f"Rs. {gst_amount:,.2f}", 0, 1, "R")
    
    pdf.ln(3)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
    
    pdf.set_font("Arial", "B", 12)
    pdf.cell(140, 8, "TOTAL AMOUNT:", 0, 0)
    pdf.cell(50, 8, f"Rs. {total:,.2f}", 0, 1, "R")
    
    # Footer
    pdf.ln(15)
    pdf.set_font("Arial", "I", 8)
    pdf.cell(0, 5, f"Generated by Atlas Freight Audit System on {datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 1, "C")
    pdf.cell(0, 5, "This is a computer-generated document.", 0, 1, "C")
    
    pdf.output(output_path)


def generate_pdf_reportlab(invoice: dict, output_path: str):
    """Generate invoice PDF using ReportLab library"""
    from reportlab.pdfgen import canvas
    from reportlab.lib.pagesizes import A4
    
    c = canvas.Canvas(output_path, pagesize=A4)
    width, height = A4
    
    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawCentredString(width/2, height - 50, "TAX INVOICE")
    
    # Invoice Details
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, height - 90, f"Invoice #: {invoice['invoice_number']}")
    c.setFont("Helvetica", 10)
    c.drawString(50, height - 110, f"Date: {invoice.get('invoice_date', 'N/A')}")
    c.drawString(50, height - 125, f"Due Date: {invoice.get('due_date', 'N/A')}")
    
    # Vendor
    c.setFont("Helvetica-Bold", 11)
    c.drawString(50, height - 155, "From:")
    c.setFont("Helvetica", 10)
    c.drawString(50, height - 170, f"{invoice.get('vendor_name', 'Carrier')}")
    
    # Shipment Details
    c.setFont("Helvetica-Bold", 11)
    c.drawString(50, height - 200, "Shipment Details:")
    c.setFont("Helvetica", 10)
    c.drawString(50, height - 215, f"Origin: {invoice.get('origin', 'N/A')}")
    c.drawString(300, height - 215, f"Destination: {invoice.get('destination', 'N/A')}")
    c.drawString(50, height - 230, f"LR Number: {invoice.get('lr_number', 'N/A')}")
    
    # Amount
    base_amount = float(invoice.get('base_amount', 0) or invoice.get('amount', 0) or 0)
    gst_amount = float(invoice.get('gst_amount', 0) or base_amount * 0.18)
    total = float(invoice.get('amount', 0) or base_amount + gst_amount)
    
    c.setFont("Helvetica-Bold", 11)
    c.drawString(50, height - 270, "Charges:")
    c.setFont("Helvetica", 10)
    c.drawString(50, height - 290, "Base Freight:")
    c.drawRightString(width - 50, height - 290, f"Rs. {base_amount:,.2f}")
    c.drawString(50, height - 305, "GST (18%):")
    c.drawRightString(width - 50, height - 305, f"Rs. {gst_amount:,.2f}")
    
    c.line(50, height - 320, width - 50, height - 320)
    
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, height - 340, "TOTAL AMOUNT:")
    c.drawRightString(width - 50, height - 340, f"Rs. {total:,.2f}")
    
    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawCentredString(width/2, 50, f"Generated by Atlas Freight Audit System on {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    
    c.save()


def generate_pdf_simple(invoice: dict, output_path: str):
    """Generate a simple text-based PDF placeholder"""
    # Create a minimal PDF file manually
    invoice_num = invoice.get('invoice_number', 'UNKNOWN')
    amount = invoice.get('amount', 0)
    vendor = invoice.get('vendor_name', 'Unknown Vendor')
    
    content = f"""%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792]
   /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>
endobj
4 0 obj
<< /Length 300 >>
stream
BT
/F1 16 Tf
220 750 Td
(TAX INVOICE) Tj
0 -40 Td
/F1 12 Tf
(Invoice #: {invoice_num}) Tj
0 -20 Td
(Vendor: {vendor}) Tj
0 -20 Td
(Amount: Rs. {amount:,.2f}) Tj
0 -40 Td
(Origin: {invoice.get('origin', 'N/A')}) Tj
0 -20 Td
(Destination: {invoice.get('destination', 'N/A')}) Tj
ET
endstream
endobj
5 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000271 00000 n 
0000000623 00000 n 
trailer
<< /Size 6 /Root 1 0 R >>
startxref
701
%%EOF"""
    
    with open(output_path, 'w') as f:
        f.write(content)


def main():
    print("=" * 60)
    print("GENERATING DEMO INVOICE PDFs")
    print("=" * 60)
    
    if not DATABASE_URL:
        print("ERROR: DATABASE_URL not set in .env")
        return
    
    # Connect to PostgreSQL
    conn = psycopg2.connect(DATABASE_URL)
    cursor = conn.cursor()
    
    # Fetch invoices
    cursor.execute("""
        SELECT id, invoice_number, vendor_name, invoice_date, due_date, 
               amount, origin, destination, mode, lr_number, weight_kg
        FROM invoices
        ORDER BY created_at DESC
        LIMIT 30
    """)
    
    columns = [desc[0] for desc in cursor.description]
    invoices = [dict(zip(columns, row)) for row in cursor.fetchall()]
    
    print(f"\nFound {len(invoices)} invoices to process")
    
    generated = 0
    for inv in invoices:
        inv_id = inv['id']
        
        # Create folder for this invoice
        inv_folder = UPLOAD_DIR / inv_id.replace('/', '_').replace('\\', '_')
        inv_folder.mkdir(parents=True, exist_ok=True)
        
        pdf_path = inv_folder / "invoice.pdf"
        
        try:
            if HAS_FPDF:
                generate_pdf_fpdf(inv, str(pdf_path))
            elif HAS_REPORTLAB:
                generate_pdf_reportlab(inv, str(pdf_path))
            else:
                generate_pdf_simple(inv, str(pdf_path))
            
            # Update database with pdf_path
            relative_path = f"{inv_id}/invoice.pdf"
            cursor.execute(
                "UPDATE invoices SET pdf_path = %s WHERE id = %s",
                (relative_path, inv_id)
            )
            
            generated += 1
            print(f"  ✓ {inv['invoice_number']} -> {pdf_path.name}")
            
        except Exception as e:
            print(f"  ✗ {inv['invoice_number']} - Error: {e}")
    
    conn.commit()
    cursor.close()
    conn.close()
    
    print(f"\n{'=' * 60}")
    print(f"COMPLETE: Generated {generated} PDFs")
    print(f"Location: {UPLOAD_DIR}")
    print(f"{'=' * 60}")


if __name__ == "__main__":
    main()
