import { jsPDF } from 'jspdf';
import { Invoice } from '../types';
import { SupplierDocument } from './supplierDocumentService';

export class PDFGeneratorService {

    // --- GENERIC HELPERS ---

    private addHeader(doc: jsPDF, title: string, subtitle?: string) {
        doc.setFontSize(22);
        doc.setTextColor(40, 40, 40);
        doc.text(title.toUpperCase(), 105, 20, { align: 'center' });

        if (subtitle) {
            doc.setFontSize(12);
            doc.setTextColor(100, 100, 100);
            doc.text(subtitle, 105, 28, { align: 'center' });
        }

        // Divider line
        doc.setLineWidth(0.5);
        doc.setDrawColor(200, 200, 200);
        doc.line(20, 35, 190, 35);
    }

    private addFooter(doc: jsPDF, isVerified: boolean = true) {
        const pageHeight = doc.internal.pageSize.height;
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`Generated by The LedgerOne System • ${new Date().toLocaleString()}`, 105, pageHeight - 10, { align: 'center' });

        if (isVerified) {
            // "Digitally Verified" Stamp
            doc.setDrawColor(0, 200, 5);
            doc.setTextColor(0, 200, 5);
            doc.setFontSize(10);
            doc.rect(140, pageHeight - 40, 50, 20);
            doc.text("DIGITALLY SIGNED", 165, pageHeight - 32, { align: 'center' });
            doc.text("VERIFIED", 165, pageHeight - 24, { align: 'center' });
        }
    }

    // --- SPECIFIC DOCUMENT GENERATORS ---

    // 1. GST CERTIFICATE
    generateGSTCertificate(supplierName: string, gstin: string, date: string): Blob {
        const doc = new jsPDF();

        // Watermark
        doc.setTextColor(240, 240, 240);
        doc.setFontSize(60);
        doc.text("GOVT OF INDIA", 105, 150, { align: 'center', angle: 45 });

        this.addHeader(doc, "GST REGISTRATION CERTIFICATE", "Government of India");

        // Content
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(12);
        let y = 50;

        doc.text(`Registration Number (GSTIN): ${gstin}`, 20, y); y += 10;
        doc.text(`Legal Name: ${supplierName}`, 20, y); y += 10;
        doc.text(`Trade Name: ${supplierName}`, 20, y); y += 10;
        doc.text(`Constitution of Business: Private Limited Company`, 20, y); y += 10;
        doc.text(`Date of Liability: ${date}`, 20, y); y += 20;

        doc.text("Principal Place of Business:", 20, y); y += 10;
        doc.setFontSize(10);
        doc.text("Plot No. 123, Industrial Area, MIDC, Andheri East, Mumbai, Maharashtra - 400093", 20, y);

        this.addFooter(doc);
        return doc.output('blob');
    }

    // 2. PAN CARD (Simulated Document)
    generatePANCard(supplierName: string, pan: string): Blob {
        const doc = new jsPDF();

        // Card Background
        doc.setFillColor(245, 245, 255);
        doc.rect(50, 80, 110, 70, 'F');
        doc.setDrawColor(0, 0, 0);
        doc.rect(50, 80, 110, 70); // Border

        doc.setFontSize(10);
        doc.setTextColor(0, 0, 0);
        doc.text("INCOME TAX DEPARTMENT", 105, 90, { align: 'center' });
        doc.setFont("helvetica");
        doc.setFont("helvetica", "bold");
        doc.text("GOVT. OF INDIA", 105, 95, { align: 'center' });

        doc.setFont("helvetica", "normal");
        doc.setFontSize(14);
        doc.text(pan, 105, 115, { align: 'center' }); // PAN Number

        doc.setFontSize(10);
        doc.text(supplierName.toUpperCase(), 60, 130);
        doc.text("Incorporation: 01/04/2010", 60, 140);

        this.addFooter(doc);
        return doc.output('blob');
    }

    // 3. VEHICLE RC
    generateRC(vehicleNo: string, owner: string, chassis: string): Blob {
        const doc = new jsPDF();
        this.addHeader(doc, "CERTIFICATE OF REGISTRATION", "Transport Department, Government of Maharashtra");

        let y = 60;
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);

        const row = (label: string, val: string) => {
            doc.setFont("helvetica", "bold");
            doc.text(label, 30, y);
            doc.setFont("helvetica", "normal");
            doc.text(val, 90, y);
            y += 12;
        };

        row("Registration No:", vehicleNo);
        row("Owner Name:", owner);
        row("Registration Date:", "12/05/2023");
        row("Chassis No:", chassis);
        row("Engine No:", `ENG-${Math.floor(Math.random() * 100000)}`);
        row("Vehicle Class:", "Heavy Goods Vehicle");
        row("Fuel Type:", "DIESEL");
        row("Maker Model:", "TATA LPT 3118");

        this.addFooter(doc);
        return doc.output('blob');
    }

    // 4. INVOICE PDF
    generateInvoice(data: Invoice): Blob {
        const doc = new jsPDF();

        // Header
        doc.setFillColor(240, 250, 240);
        doc.rect(0, 0, 210, 40, 'F');
        doc.setFontSize(24);
        doc.setTextColor(0, 100, 0);
        doc.text("TAX INVOICE", 180, 25, { align: 'right' });

        doc.setFontSize(16);
        doc.setTextColor(0, 0, 0);
        doc.text("TCI Express Ltd.", 20, 20);
        doc.setFontSize(10);
        doc.text("GSTIN: 27AABCT1234F1Z5", 20, 28);

        let y = 60;

        // Invoice Details Grid
        doc.line(20, y - 5, 190, y - 5);
        doc.setFont("helvetica", "bold");
        doc.text(`Invoice #: ${data.id}`, 20, y);
        doc.text(`Date: ${data.date}`, 140, y);
        y += 10;
        doc.text(`Due Date: ${data.dueDate}`, 140, y);
        y += 20;

        // Bill To
        doc.setFillColor(240, 240, 240);
        doc.rect(20, y, 80, 30, 'F');
        doc.text("Bill To:", 25, y + 8);
        doc.setFont("helvetica", "normal");
        doc.text("Tata Steel Ltd.", 25, y + 16);
        doc.text("Jamshedpur, Jharkhand", 25, y + 22);

        y += 50;

        // Table Header
        doc.setFillColor(50, 50, 50);
        doc.rect(20, y, 170, 10, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFont("helvetica", "bold");
        doc.text("Description", 25, y + 7);
        doc.text("Amount", 160, y + 7);

        y += 10;

        // Items (Mock Line Items based on total)
        doc.setTextColor(0, 0, 0);
        doc.setFont("helvetica", "normal");

        doc.text(`Freight Charges - Ref: ${data.poNumber || 'N/A'}`, 25, y + 10);
        doc.text(new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(data.amount * 0.9), 160, y + 10); // Base Amount
        y += 20;

        doc.text(`GST (18%)`, 25, y + 10);
        doc.text(new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(data.amount * 0.1), 160, y + 10); // Tax
        y += 20;

        // Total
        doc.setLineWidth(0.5);
        doc.line(120, y, 190, y);
        y += 10;
        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.text("TOTAL:", 120, y);
        doc.text(new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(data.amount), 160, y);

        // Footer
        this.addFooter(doc, true);

        return doc.output('blob');
    }

    // 5. GENERIC DOC (Fallback)
    generateGenericDoc(title: string, content: Record<string, string>): Blob {
        const doc = new jsPDF();
        this.addHeader(doc, title);

        let y = 60;
        doc.setFontSize(12);

        Object.entries(content).forEach(([key, value]) => {
            doc.setFont("helvetica", "bold");
            doc.text(`${key}:`, 30, y);
            doc.setFont("helvetica", "normal");
            doc.text(`${value}`, 80, y);
            y += 12;
        });

        this.addFooter(doc);
        return doc.output('blob');
    }

    // 6. EXECUTIVE REPORT - BLOOMBERG STYLE
    // Colors: White, Black, Robinhood Green, IBM Blue
    generateExecutiveReport(): Blob {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.width;
        const pageHeight = doc.internal.pageSize.height;

        const reportDate = new Date().toLocaleDateString('en-IN', {
            day: '2-digit', month: 'long', year: 'numeric'
        });
        const reportId = `RPT-${Date.now().toString(36).toUpperCase()}`;

        // ==================== PAGE 1: COVER ====================
        // Black header bar
        doc.setFillColor(0, 0, 0);
        doc.rect(0, 0, pageWidth, 50, 'F');

        // 3D Geometric Icon (Cube shape)
        doc.setFillColor(0, 200, 5);
        doc.rect(15, 15, 20, 20, 'F');
        doc.setFillColor(0, 150, 5);
        doc.triangle(35, 15, 35, 35, 45, 25, 'F');
        doc.setFillColor(0, 180, 5);
        doc.triangle(15, 15, 35, 15, 25, 5, 'F');

        // Title
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(24);
        doc.setFont("helvetica", "bold");
        doc.text("ATLAS CONTROL TOWER", 50, 25);
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.text("FREIGHT AUDIT & ANALYTICS PLATFORM", 50, 35);

        // Green accent line
        doc.setFillColor(0, 200, 5);
        doc.rect(0, 50, pageWidth, 3, 'F');

        // Report Title
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(28);
        doc.setFont("helvetica", "bold");
        doc.text("EXECUTIVE SUMMARY REPORT", pageWidth / 2, 80, { align: 'center' });

        doc.setFontSize(12);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(100, 100, 100);
        doc.text(`Report Date: ${reportDate}`, pageWidth / 2, 92, { align: 'center' });
        doc.text(`Report ID: ${reportId}`, pageWidth / 2, 100, { align: 'center' });

        // Status Badge
        doc.setFillColor(0, 200, 5);
        doc.roundedRect(75, 110, 60, 12, 2, 2, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        doc.text("SYSTEM STATUS: OPTIMAL", 105, 118, { align: 'center' });

        // KPI Summary Box
        let y = 140;
        doc.setFillColor(240, 240, 240);
        doc.rect(15, y, pageWidth - 30, 80, 'F');
        doc.setDrawColor(0, 0, 0);
        doc.setLineWidth(0.5);
        doc.rect(15, y, pageWidth - 30, 80);

        doc.setTextColor(0, 0, 0);
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text("KEY PERFORMANCE INDICATORS", 20, y + 15);

        // KPI Grid (2x2)
        const kpis = [
            { label: 'TOTAL FREIGHT SPEND', value: '₹164.8M', change: '+12.4%', positive: false },
            { label: 'COST SAVINGS', value: '₹8.2M', change: '+₹1.8M vs Target', positive: true },
            { label: 'INVOICES PROCESSED', value: '4,695', change: '68% Automated', positive: true },
            { label: 'ANOMALIES DETECTED', value: '108', change: '₹2.4M Prevented', positive: true },
        ];

        let kpiX = 25;
        let kpiY = y + 30;
        kpis.forEach((kpi, index) => {
            if (index === 2) { kpiX = 25; kpiY += 25; }

            doc.setFontSize(8);
            doc.setFont("helvetica", "normal");
            doc.setTextColor(100, 100, 100);
            doc.text(kpi.label, kpiX, kpiY);

            doc.setFontSize(18);
            doc.setFont("helvetica", "bold");
            doc.setTextColor(0, 0, 0);
            doc.text(kpi.value, kpiX, kpiY + 10);

            doc.setFontSize(9);
            doc.setTextColor(kpi.positive ? 0 : 200, kpi.positive ? 200 : 0, kpi.positive ? 5 : 0);
            doc.text(kpi.change, kpiX + 45, kpiY + 10);

            kpiX += 85;
        });

        // Footer
        doc.setFillColor(0, 0, 0);
        doc.rect(0, pageHeight - 20, pageWidth, 20, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(8);
        doc.text("CONFIDENTIAL - FOR INTERNAL USE ONLY", pageWidth / 2, pageHeight - 12, { align: 'center' });
        doc.text(`Generated by ATLAS • ${reportDate}`, pageWidth / 2, pageHeight - 6, { align: 'center' });

        // ==================== PAGE 2: SPEND ANALYSIS ====================
        doc.addPage();

        // Header
        doc.setFillColor(0, 0, 0);
        doc.rect(0, 0, pageWidth, 25, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text("FREIGHT SPEND ANALYSIS", 15, 16);
        doc.setFontSize(8);
        doc.text(`Page 2 | ${reportDate}`, pageWidth - 15, 16, { align: 'right' });

        // Green line
        doc.setFillColor(0, 200, 5);
        doc.rect(0, 25, pageWidth, 2, 'F');

        y = 40;

        // Spend Overview Table
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text("Monthly Spend Overview (YTD)", 15, y);
        y += 10;

        // Table Header
        doc.setFillColor(0, 0, 0);
        doc.rect(15, y, pageWidth - 30, 8, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(8);
        doc.text("MONTH", 20, y + 5.5);
        doc.text("ACTUAL", 55, y + 5.5);
        doc.text("BUDGET", 85, y + 5.5);
        doc.text("VARIANCE", 115, y + 5.5);
        doc.text("STATUS", 155, y + 5.5);
        y += 8;

        const monthlyData = [
            { month: 'January', actual: '₹18.5M', budget: '₹19.0M', variance: '-2.6%', positive: true },
            { month: 'February', actual: '₹19.2M', budget: '₹19.5M', variance: '-1.5%', positive: true },
            { month: 'March', actual: '₹20.1M', budget: '₹20.0M', variance: '+0.5%', positive: false },
            { month: 'April', actual: '₹19.8M', budget: '₹20.5M', variance: '-3.4%', positive: true },
            { month: 'May', actual: '₹21.3M', budget: '₹21.0M', variance: '+1.4%', positive: false },
            { month: 'June', actual: '₹20.5M', budget: '₹21.5M', variance: '-4.7%', positive: true },
            { month: 'July', actual: '₹22.1M', budget: '₹22.0M', variance: '+0.5%', positive: false },
            { month: 'August', actual: '₹21.8M', budget: '₹22.5M', variance: '-3.1%', positive: true },
            { month: 'September', actual: '₹23.2M', budget: '₹23.0M', variance: '+0.9%', positive: false },
        ];

        monthlyData.forEach((row, index) => {
            if (index % 2 === 0) {
                doc.setFillColor(240, 240, 240);
                doc.rect(15, y, pageWidth - 30, 8, 'F');
            }
            doc.setTextColor(0, 0, 0);
            doc.setFontSize(8);
            doc.text(row.month, 20, y + 5.5);
            doc.text(row.actual, 55, y + 5.5);
            doc.text(row.budget, 85, y + 5.5);
            doc.setTextColor(row.positive ? 0 : 200, row.positive ? 200 : 0, row.positive ? 5 : 0);
            doc.text(row.variance, 115, y + 5.5);

            // Status indicator
            doc.setFillColor(row.positive ? 0 : 200, row.positive ? 200 : 0, row.positive ? 5 : 0);
            doc.circle(160, y + 4, 2, 'F');
            doc.setTextColor(0, 0, 0);
            doc.text(row.positive ? 'UNDER' : 'OVER', 165, y + 5.5);
            y += 8;
        });

        // Summary box
        y += 10;
        doc.setFillColor(0, 67, 206);
        doc.rect(15, y, pageWidth - 30, 25, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(10);
        doc.setFont("helvetica", "bold");
        doc.text("SUMMARY", 20, y + 8);
        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        doc.text("Total YTD Spend: ₹164.8M | Budget: ₹169.0M | Variance: -₹4.2M (Under Budget)", 20, y + 18);

        // ==================== PAGE 3: CARRIER PERFORMANCE ====================
        doc.addPage();

        // Header
        doc.setFillColor(0, 0, 0);
        doc.rect(0, 0, pageWidth, 25, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text("CARRIER PERFORMANCE MATRIX", 15, 16);
        doc.setFontSize(8);
        doc.text(`Page 3 | ${reportDate}`, pageWidth - 15, 16, { align: 'right' });

        doc.setFillColor(0, 200, 5);
        doc.rect(0, 25, pageWidth, 2, 'F');

        y = 40;

        doc.setTextColor(0, 0, 0);
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text("Top Carrier Performance (By Volume)", 15, y);
        y += 10;

        // Table Header
        doc.setFillColor(0, 0, 0);
        doc.rect(15, y, pageWidth - 30, 8, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(8);
        doc.text("CARRIER", 20, y + 5.5);
        doc.text("VOLUME", 60, y + 5.5);
        doc.text("ON-TIME %", 90, y + 5.5);
        doc.text("COST SCORE", 125, y + 5.5);
        doc.text("QUALITY", 160, y + 5.5);
        y += 8;

        const carrierData = [
            { carrier: 'TCI Express', volume: '2,450', onTime: '98.2%', cost: '92', quality: '96' },
            { carrier: 'Blue Dart', volume: '1,890', onTime: '95.8%', cost: '88', quality: '94' },
            { carrier: 'Delhivery', volume: '1,650', onTime: '93.5%', cost: '95', quality: '91' },
            { carrier: 'Gati KWE', volume: '1,420', onTime: '91.2%', cost: '89', quality: '88' },
            { carrier: 'DTDC', volume: '980', onTime: '89.5%', cost: '94', quality: '86' },
            { carrier: 'Safexpress', volume: '1,250', onTime: '94.1%', cost: '86', quality: '92' },
        ];

        carrierData.forEach((row, index) => {
            if (index % 2 === 0) {
                doc.setFillColor(240, 240, 240);
                doc.rect(15, y, pageWidth - 30, 8, 'F');
            }
            doc.setTextColor(0, 0, 0);
            doc.setFontSize(8);
            doc.text(row.carrier, 20, y + 5.5);
            doc.text(row.volume, 60, y + 5.5);

            const onTimeNum = parseFloat(row.onTime);
            doc.setTextColor(onTimeNum >= 95 ? 0 : 200, onTimeNum >= 95 ? 200 : 150, onTimeNum >= 95 ? 5 : 0);
            doc.text(row.onTime, 90, y + 5.5);

            doc.setTextColor(0, 0, 0);
            doc.text(row.cost, 130, y + 5.5);
            doc.text(row.quality, 165, y + 5.5);
            y += 8;
        });

        // ==================== PAGE 4: ANOMALY & FRAUD DETECTION ====================
        doc.addPage();

        // Header
        doc.setFillColor(0, 0, 0);
        doc.rect(0, 0, pageWidth, 25, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text("ANOMALY DETECTION & FRAUD PREVENTION", 15, 16);
        doc.setFontSize(8);
        doc.text(`Page 4 | ${reportDate}`, pageWidth - 15, 16, { align: 'right' });

        doc.setFillColor(0, 200, 5);
        doc.rect(0, 25, pageWidth, 2, 'F');

        y = 40;

        // Anomaly Summary
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text("Detection Summary (Last 8 Weeks)", 15, y);
        y += 15;

        // 3 stat boxes
        const statBoxWidth = 55;

        // Box 1 - DETECTED (IBM Blue)
        doc.setFillColor(0, 67, 206);
        doc.rect(15, y, statBoxWidth, 30, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(8);
        doc.text('DETECTED', 15 + statBoxWidth / 2, y + 8, { align: 'center' });
        doc.setFontSize(18);
        doc.setFont("helvetica", "bold");
        doc.text('108', 15 + statBoxWidth / 2, y + 22, { align: 'center' });

        // Box 2 - RESOLVED (Green)
        doc.setFillColor(0, 200, 5);
        doc.rect(80, y, statBoxWidth, 30, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.text('RESOLVED', 80 + statBoxWidth / 2, y + 8, { align: 'center' });
        doc.setFontSize(18);
        doc.setFont("helvetica", "bold");
        doc.text('97', 80 + statBoxWidth / 2, y + 22, { align: 'center' });

        // Box 3 - SAVINGS (Black)
        doc.setFillColor(0, 0, 0);
        doc.rect(145, y, statBoxWidth, 30, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.text('SAVINGS', 145 + statBoxWidth / 2, y + 8, { align: 'center' });
        doc.setFontSize(18);
        doc.setFont("helvetica", "bold");
        doc.text('₹2.4M', 145 + statBoxWidth / 2, y + 22, { align: 'center' });

        y += 50;

        // Benford's Law Analysis
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text("Benford's Law Conformance Analysis", 15, y);
        y += 8;

        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(100, 100, 100);
        doc.text("Statistical analysis of first-digit distribution in invoice amounts", 15, y);
        y += 12;

        // Benford table
        doc.setFillColor(0, 0, 0);
        doc.rect(15, y, pageWidth - 30, 8, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(8);
        doc.text("DIGIT", 25, y + 5.5);
        doc.text("EXPECTED %", 55, y + 5.5);
        doc.text("ACTUAL %", 95, y + 5.5);
        doc.text("DEVIATION", 135, y + 5.5);
        doc.text("STATUS", 170, y + 5.5);
        y += 8;

        const benfordData = [
            { digit: '1', expected: '30.1', actual: '28.5', deviation: '-1.6' },
            { digit: '2', expected: '17.6', actual: '18.2', deviation: '+0.6' },
            { digit: '3', expected: '12.5', actual: '13.1', deviation: '+0.6' },
            { digit: '4', expected: '9.7', actual: '9.2', deviation: '-0.5' },
            { digit: '5', expected: '7.9', actual: '8.5', deviation: '+0.6' },
        ];

        benfordData.forEach((row, index) => {
            if (index % 2 === 0) {
                doc.setFillColor(240, 240, 240);
                doc.rect(15, y, pageWidth - 30, 8, 'F');
            }
            doc.setTextColor(0, 0, 0);
            doc.setFontSize(8);
            doc.text(row.digit, 30, y + 5.5);
            doc.text(row.expected + '%', 60, y + 5.5);
            doc.text(row.actual + '%', 100, y + 5.5);
            doc.text(row.deviation + '%', 140, y + 5.5);

            doc.setFillColor(0, 200, 5);
            doc.circle(175, y + 4, 2, 'F');
            doc.setTextColor(0, 0, 0);
            doc.text('OK', 180, y + 5.5);
            y += 8;
        });

        y += 10;
        doc.setFillColor(0, 200, 5);
        doc.rect(15, y, pageWidth - 30, 20, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(10);
        doc.setFont("helvetica", "bold");
        doc.text("COMPLIANCE STATUS: PASSED", 20, y + 8);
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.text("Chi-Square Test p-value = 0.847 | Data conforms to expected Benford distribution", 20, y + 15);

        // Final page footer
        doc.setFillColor(0, 0, 0);
        doc.rect(0, pageHeight - 20, pageWidth, 20, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(8);
        doc.text("END OF REPORT | ATLAS CONTROL TOWER | POWERED BY SEQUELSTRING AI", pageWidth / 2, pageHeight - 8, { align: 'center' });

        return doc.output('blob');
    }
}

export const pdfGenerator = new PDFGeneratorService();
